// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAf7LJIyzGgIBod1rRtuxwHr7CEBNUiBSE',
    appId: '1:382543890178:web:68b628084b5a292e07e41b',
    messagingSenderId: '382543890178',
    projectId: 'project-1-31624',
    authDomain: 'project-1-31624.firebaseapp.com',
    storageBucket: 'project-1-31624.firebasestorage.app',
    measurementId: 'G-TQSV9TX0JN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDwUQf9QH-B8dagNyAiI8hlV4sLj5Upt8',
    appId: '1:382543890178:android:d2a5ae1912062b4c07e41b',
    messagingSenderId: '382543890178',
    projectId: 'project-1-31624',
    storageBucket: 'project-1-31624.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEI5a_B3iHmcwQrRPCVsgilHrerpzkQ04',
    appId: '1:382543890178:ios:1ddd61591e9579c207e41b',
    messagingSenderId: '382543890178',
    projectId: 'project-1-31624',
    storageBucket: 'project-1-31624.firebasestorage.app',
    iosBundleId: 'com.example.prodhunt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEI5a_B3iHmcwQrRPCVsgilHrerpzkQ04',
    appId: '1:382543890178:ios:1ddd61591e9579c207e41b',
    messagingSenderId: '382543890178',
    projectId: 'project-1-31624',
    storageBucket: 'project-1-31624.firebasestorage.app',
    iosBundleId: 'com.example.prodhunt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAf7LJIyzGgIBod1rRtuxwHr7CEBNUiBSE',
    appId: '1:382543890178:web:62507667b14f326c07e41b',
    messagingSenderId: '382543890178',
    projectId: 'project-1-31624',
    authDomain: 'project-1-31624.firebaseapp.com',
    storageBucket: 'project-1-31624.firebasestorage.app',
    measurementId: 'G-5TNV3TL1S8',
  );
}
